### PR TITLE
Not only TensorType for Intput-Output params

### PR DESCRIPTION
**Pull request by ikrivosheev**
Hello! When I tried to create `Session` I got error: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PointerShouldNotBeNull("CastTypeInfoToTensorInfo")'
``` 

I made small research and find java bindings for onnxruntime: https://github.com/microsoft/onnxruntime/blob/6832b688a2848f64d4d43ac0084c6609aa0203bc/java/src/main/native/OrtJniUtil.c.

I made something close to the implementation.

### CODE REVIEW

**Comment by ikrivosheev** [comment]
This is breaking changes for `API`. If it's ok - I can fix tests. Or I'm open to suggestions)

**Review by decahedron1 — APPROVED** [review]
This is a great start for supporting sequences & maps! I'd like to merge this into the [v2 branch](https://github.com/pykeio/ort/tree/v2) since it is a breaking API change, could you port these changes over to there? I think it would require creating a new PR.

**Comment by ikrivosheev** [comment]
> This is a great start for supporting sequences & maps! I'd like to merge this into the [v2 branch](https://github.com/pykeio/ort/tree/v2) since it is a breaking API change, could you port these changes over to there? I think it would require creating a new PR.

Yes, I will do it.

**Comment by ikrivosheev** [comment]
@decahedron1 I rebased from v2 branch)

**Pull request merged**
