### PR TITLE
v2.0

### LINKED ISSUE #97: error[E0597]: `XXX` does not live long enough
Hi,

Together with my colleague, @aykut-bozkurt, we have been trying out `ort` with Hugging Face's `tokenizers` library. We wanted to run [`intfloat/e5-small-v2`](https://huggingface.co/intfloat/e5-small-v2) with the following dependencies:

```toml
# Cargo.toml

[package]
name = "embedding-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.0"
ort = { version = "1.15.0", features = ["cuda"] }
tokenizers = { version = "0.14.0", default-features = false, features = ["esaxx_fast", "onig"] }
```

and the following source file:

```rust
// src/main.rs

use std::path::PathBuf;

use ndarray;
use ort;
use tokenizers;

fn main() {
    let tokenizer_path = PathBuf::from("models")
        .join(format!("tokenizer-e5-{}-v2", "small"))
        .join("tokenizer.json");
    let tokenizer =
        tokenizers::tokenizer::Tokenizer::from_file(tokenizer_path.to_str().unwrap()).unwrap();

    let mut encodings = tokenizer.encode_batch(vec![
      "query: how much protein should a female eat",
      "query: summit define",
      "passage: As a general guideline, the CDC's average requirement of protein for women ages 19 to 70 is 46 grams per day. But, as you can see from this chart, you'll need to increase that if you're expecting or training for a marathon. Check out the chart below to see how much protein you should be eating each day.",
      "passage: Definition of summit for English Language Learners. : 1  the highest point of a mountain : the top of a mountain. : 2  the highest level. : 3  a meeting or series of meetings between the leaders of two or more governments."
    ], true).unwrap();

    let model_path = PathBuf::from("models").join(format!("model-e5-{}-v2.onnx", "small"));
    let ort_env = ort::Environment::builder()
        .with_name("ortenv")
        .build()
        .unwrap();
    let session = ort::SessionBuilder::new(&ort_env.into_arc())
        .unwrap()
        .with_model_from_file(model_path)
        .unwrap();

    // Get input and output names
    println!("input_name: {:?}", session.inputs);
    println!("output_name: {:?}", session.outputs);

    let (input_ids, attention_mask, token_type_ids) = encodings.iter_mut().fold(
        (Vec::new(), Vec::new(), Vec::new()),
        |(mut input_ids, mut attention_mask, mut token_type_ids), encoding| {
            encoding.pad(
                512,
                u32::MAX,
                u32::MAX,
                "[PAD]",
                tokenizers::PaddingDirection::Right,
            );
            encoding.truncate(512, 0, tokenizers::TruncationDirection::Right);
            input_ids.extend(encoding.get_ids().iter().map(|item| *item as i64));
            attention_mask.extend(
                encoding
                    .get_attention_mask()
                    .iter()
                    .map(|item| *item as i64),
            );
            token_type_ids.extend(encoding.get_type_ids().iter().map(|item| *item as i64));
            (input_ids, attention_mask, token_type_ids)
        },
    );

    // Run inference
    let batch_size = encodings.len();
    let sequence_length = 512;

    let input_ids = ndarray::CowArray::from(&input_ids)
        .into_shape((batch_size, sequence_length))
        .unwrap()
        .into_dyn();
    let input_ids = ort::Value::from_array(session.allocator(), &input_ids).unwrap();

    print!("input_ids: {:?}", input_ids);

    let attention_mask = ndarray::CowArray::from(&attention_mask)
        .into_shape((batch_size, sequence_length))
        .unwrap()
        .into_dyn();
    let attention_mask = ort::Value::from_array(session.allocator(), &attention_mask).unwrap();

    print!("attention_mask: {:?}", attention_mask);

    let token_type_ids = ndarray::CowArray::from(&token_type_ids)
        .into_shape((batch_size, sequence_length))
        .unwrap()
        .into_dyn();
    let token_type_ids = ort::Value::from_array(session.allocator(), &token_type_ids).unwrap();

    print!("token_type_ids: {:?}", token_type_ids);

    let output = session
        .run(vec![input_ids, attention_mask, token_type_ids])
        .unwrap();
    print!("output: {:?}", output)
}
```

When we try to compile the code, we get the following error:

```cmd
$ cargo run --release
   Compiling embedding-playground v0.1.0 (/home/aytekinar/Projects/work/embedding-playground)
error[E0597]: `attention_mask` does not live long enough
  --> src/main.rs:74:70
   |
70 |     let attention_mask = ndarray::CowArray::from(&attention_mask)
   |         -------------- binding `attention_mask` declared here
...
74 |     let attention_mask = ort::Value::from_array(session.allocator(), &attention_mask).unwrap();
   |                                                                      ^^^^^^^^^^^^^^^ borrowed value does not live long enough
...
90 | }
   | -
   | |
   | `attention_mask` dropped here while still borrowed
   | borrow might be used here, when `input_ids` is dropped and runs the `Drop` code for type `Value`
   |
   = note: values in a scope are dropped in the opposite order they are defined

error[E0597]: `token_type_ids` does not live long enough
  --> src/main.rs:82:70
   |
78 |     let token_type_ids = ndarray::CowArray::from(&token_type_ids)
   |         -------------- binding `token_type_ids` declared here
...
82 |     let token_type_ids = ort::Value::from_array(session.allocator(), &token_type_ids).unwrap();
   |                                                                      ^^^^^^^^^^^^^^^ borrowed value does not live long enough
...
90 | }
   | -
   | |
   | `token_type_ids` dropped here while still borrowed
   | borrow might be used here, when `input_ids` is dropped and runs the `Drop` code for type `Value`
   |
   = note: values in a scope are dropped in the opposite order they are defined

For more information about this error, try `rustc --explain E0597`.
error: could not compile `embedding-playground` (bin "embedding-playground") due to 2 previous errors
```

First, are we using the libraries as they are supposed to be used? We could not find an example that uses multiple inputs (from the `tokenizers` library). Is this a limitation on `ort`'s or `ndarray`'s side? Otherwise, what would you recommend?

### PR DESCRIPTION
**Pull request by decahedron1**
- Refactor session inputs/outputs to allow specifying inputs/retrieving outputs by name.
- Accept more `ndarray` types for better ergonomics & performance: no more `into_dyn()` or `CowArray::from` in most cases
- Make `IoBinding` more clear and easier to use by merging it into `Session::run`.
- Make `SessionBuilder` cloneable (https://github.com/pykeio/ort/issues/70)
- Address unsoundness issues (https://github.com/pykeio/ort/issues/69)
- Fix `Value` lifetimes (https://github.com/pykeio/ort/issues/74)
- Add YOLOv8 example.
- Follow SemVer convention.

Fixes #97, #80, #70, #69, #66

## TODO
- [ ] Add logic to convert between `Value`s and `HashMap`/`Vec` for map/sequence types as discussed in #30 
- [x] Identify & fix any remaining memory leaks or performance pitfalls.
- [x] Ensure new input/output system is not flaky, make sure dropping `Value`s isn't bug prone. Related: #105
- [x] See if we can further reduce memory allocations in hot paths #80
- [x] Create a docs site and add more examples for common models, both simple & complex.
- [x] Add tests/examples for IoBinding and ensure it's usable and working as intended #88 #66
- [ ] See if I can get my hands on hardware to test NN-API and ROCm EPs #45 #16
- [x] Should pyke provide prebuilt static libraries, WASM, DirectML? #28

### CODE REVIEW

**Comment by cpgddln** [comment]
Thanks for the work on this new version.

The `Session::run` method returns an `ort::Value<'static>`. Despite the `'static` lifetime, these require the `Session` to exist to refer to valid memory. The documentation notes:
  > Note that ORT-owned values will prevent the session from being dropped until all values are dropped; to prevent this behavior, extract the data with [Value::extract_tensor].

Similarly, the `OrtOwnedTensor<'static>` require the session to exist, and their `drop` method also seems to be doing some reference counting.

However, the following segfaults in the `gpt` example:
```
let outputs = session.run(inputs![&array])?;
let generated_tokens: OrtOwnedTensor<f32, _> = outputs["output1"].extract_tensor()?;
drop(outputs);
drop(session);
println!("{:?}", generated_tokens);
```
The array is properly displayed when removing the `drop`.

Either:
- It was assumed that the C-side ORT keeps the memory alive until all `Value` and `OrtOwnedTensor` have been dropped, even if the rust `Session` gets dropped. This does not seem to be the case, and the output `Value` should be tied to the lifetime of the `Session`.
- Only the `Value` does reference counting for the `Session`, in which case `extract_tensor(&'a self)` on `Value<'static>` should return a `OrtOwnedTensor<'a>`, not a `OrtOwnedTensor<'static>`

**Comment by bharrisau** [comment]
Bit of an issue with the `SessionOutputs`. `IoBinding::bind_input` takes a `Value`, but `SessionOutputs` can only give an `&Value`. So not possible to use an output as a subsequent input.

Current workaround
```rust
let outs = bind.run().unwrap();
assert!(outs.len() == 1);
let out_copy = unsafe { std::ptr::read(&outs["output0"]) };
std::mem::forget(outs); // Because we copied an Arc
bind.bind_input("images", out_copy).unwrap();
```

**Comment by decahedron1** [comment]
@bharrisau Thank you, just implemented `DerefMut` for `SessionOutputs` which allows you to move the `Value`s out like so:
```rs
let output1: Value<'_> = outputs.remove("output1").unwrap();
```

**Comment by bharrisau** [comment]
As I mentioned in #88 - there is a significant performance penalty from the `CowArray` doing an extra copy in `Value::from_array`. First `CowArray.as_standard_layout()` which either copies the array if layout is wrong, or else returns a `CowRepr::View` of the input array. Then `CowArray.as_mut_ptr()` which will result in a copy if the input is `CowRepr::View`.

Probably need another way of creating the `Value`, either taking an `&mut ArcArray`, or else creating from a slice+shape. With the `&mut ArcArray`, it looks like you could call `.as_mut_ptr()` which will skip the copy if the Arc is unique. Then call `.clone()` and save the clone until the call to `run()`, then drop the clone and it would be unique again. Should ensure only 1 mutable reference at a time.

**Comment by ikrivosheev** [comment]
@decahedron1 can you update PR description? I want to help to finish this)

**Comment by decahedron1** [comment]
@ikrivosheev Updated PR description with current status 🙂

**Comment by JewishLewish** [comment]
Referencing to [e694ebc](https://github.com/pykeio/ort/pull/78/commits/e694ebce211d3204d850193a3ebbf8168f3defd2) Commit.

symlink works smoothly on Linux 👍

**Pull request merged**
